-- ============================================================================
-- Live Action Tracker — database schema
--
-- IMPORTANT: this file was reconstructed from how the site uses the database
-- (see assets/js/stats.js). It is not an export of the live project. Before
-- trusting it, compare it against the real table in the Supabase dashboard
-- (Table Editor → email_stats) and correct this file if they differ.
--
-- Use this to recreate the backend from scratch, or to check that the security
-- rules on the live project are still correct.
--
-- Run it in the Supabase dashboard: SQL Editor → New query → Run.
-- ============================================================================

create table if not exists public.email_stats (
    id              bigint generated by default as identity primary key,
    created_at      timestamptz not null default now(),

    -- "Caspar Veldkamp (NSC)" — matches politicianLabel() in
    -- assets/js/data/politicians.js
    politician_name text not null,

    -- "Version 1" ... "Version 5" — matches the version ids in
    -- assets/js/data/campaign.js
    version_name    text not null,

    -- 'Gmail' | 'Outlook' | 'Mail App' | 'Copy All' — see ACTIONS in stats.js.
    -- Rows written before 2026-08-11 use the older 'Web Click' / 'Mobile Click',
    -- from when the page had two send buttons. The chart does not read this
    -- column, so the old values are harmless.
    action_type     text not null,

    -- Campaign id, e.g. 'executions'. Keeps campaigns' counts separate.
    topic           text not null
);

-- The chart filters by topic and counts per politician.
create index if not exists email_stats_topic_idx
    on public.email_stats (topic);

-- ============================================================================
-- Security
--
-- The key in assets/js/config.js is public: anyone reading the page can see it
-- and can call the API with it. Row Level Security is therefore the only thing
-- protecting this table. These policies deliberately allow just two things:
-- add a row, and read rows. Nobody can edit or delete existing counts.
-- ============================================================================

alter table public.email_stats enable row level security;

-- Anyone may record an action.
drop policy if exists "anon can insert actions" on public.email_stats;
create policy "anon can insert actions"
    on public.email_stats
    for insert
    to anon
    with check (true);

-- Anyone may read the counts, because the tracker is public.
drop policy if exists "anon can read actions" on public.email_stats;
create policy "anon can read actions"
    on public.email_stats
    for select
    to anon
    using (true);

-- Note: no UPDATE or DELETE policy exists, so those are refused for anon.
-- Do not add them. Do not put a service_role key in the website.

-- ============================================================================
-- Privacy
--
-- No personal data belongs in this table. The visitor's name, city and email
-- text stay in their browser and are never sent here. If you add a column,
-- keep it that way.
-- ============================================================================
